# Generated by Django 5.2.1 on 2025-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
