# Generated by Django 5.2.1 on 2025-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-created_at']},
        ),
    ]
